name: Create terraform release
on:
  release:
    types: [published]

jobs:
  release-job:
    runs-on: ubuntu-latest
    env:
      ARCHIVE_NAME: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          path: terraform
      - name: create-archive
        run: tar -czf "${{ env.ARCHIVE_NAME }}".tar.gz terraform
      - name: upload-archive
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ARCHIVE_NAME }}.tar.gz
          asset_name: ${{ env.ARCHIVE_NAME }}.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
