name: Test matrix from yaml

on:
  workflow_dispatch:

jobs:
  read:
    name: Read YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read YAML file
        id: yaml
        run: |
          echo 'variables<<EOF' >> $GITHUB_OUTPUT
          cat ./.github/workflows/yaml/matrix.yaml >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
    outputs:
      variables: ${{ steps.yaml.outputs.variables }}

  debug:
    name: Debug
    needs: read
    runs-on: ubuntu-latest
    steps:
      - run: echo  "variables = ${{ needs.read.outputs.variables }}"

  run:
    name: Test matrix job from yaml
    needs: read
    uses: dmytro-dorofeiev/shared-workflows/.github/workflows/matrix-yaml.yaml@main
    with:
      matrix: ${{ needs.read.outputs.variables }}
